apiVersion: v1
kind: Pod
metadata:
  labels:
    sidecar: gcpdeploy
  namespace: jenkins
spec:
  serviceAccount: jenkins
  containers:
  - name: gcpdeploy
    image: gcr.io/arquitetura-207620/gcpdeploy:v0.3.0
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/jenkins-gcp-credentials.json       
    #imagePullPolicy: Always
    command: 
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-gcp-secret
      mountPath: /secret      
  volumes:
    - name: kaniko-gcp-secret
      secret:
        secretName: kaniko-gcp-credentials-secret         