apiVersion: v1
kind: Pod
metadata:
  name: golang-agent
  labels:
    app: golang
  namespace: jenkins
spec:
  containers:
  - name: golang
    image: golang:1.12
    #imagePullPolicy: Always
    command: 
    - cat
    tty: true