apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pbdeploy
  namespace: jenkins
spec:
  serviceAccount: jenkins
  containers:
  - name: pbdeploy
    image: gcr.io/arquitetura-207620/pbdeploy:v0.3.0
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/jenkins-gcp-credentials.json       
    #imagePullPolicy: Always
    command: 
    - cat
    tty: true
    volumeMounts:
    - name: jenkins-gcp-credentials
      mountPath: /secret      
  volumes:
    - name: jenkins-gcp-credentials
      secret:
        secretName: jenkins-gcp-credentials         