apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sonar-scanner-cli
  namespace: jenkins
spec:
  containers:
  - name: sonar-scanner-cli
    image: docker.io/sonarsource/sonar-scanner-cli:4
    #imagePullPolicy: Always
    command: 
    - cat
    tty: true
