kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "appchart.fullname" . }}
  labels:
    {{- include "appchart.labels" . | nindent 4 }}
data:
{{- /*
  # Example:
  myconfig: {{ .Values.myconfig | b64enc }}
  myconfig: VGhpcyBpcyBteSBjb25maWcgIQ== 
*/ -}}