{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "appchart.fullname" . }}
  labels:
    {{- include "appchart.labels" . | nindent 4 }} 
spec:
  hosts:
  {{- range .Values.istio.hosts }}
  - {{ .host | quote }}
  {{- end }}
  gateways:
  - {{ include "appchart.fullname" . }}
  http:
  - match:
    {{- range .Values.istio.paths }}
    - uri:
        prefix: {{ . | quote }}
    {{- end }} 
    route:
    - destination:
        host: {{ include "appchart.serviceClusterFQDN" . }}
        port:
          number: {{ .Values.service.port }} 
{{- end }}